name: deploy timmermannetjes/bocks_connector

# only update when release is done.
on:
  push:
    tags: "v[0-9].[0-9].[0-9]"

# replaced with local settings
jobs:
  balena-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: balena CLI Action
        uses: balena-community/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_TOKEN}}
          balena_cli_commands: >
            push jeroen5/blocks_connector --release-tag release ${{ github.ref_name }};
          balena_cli_version: 13.7.1
